"""OpenAI analyst agent for AI-Stock-Radar."""

import os
from pathlib import Path

import pandas as pd
from agents import Agent, Runner
from dotenv import load_dotenv


PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

ENV_PATH = PROJECT_ROOT / ".env"

LATEST_REPORT_PATH = (
    PROJECT_ROOT
    / "data"
    / "reports"
    / "radar_latest.csv"
)

AI_REPORT_PATH = (
    PROJECT_ROOT
    / "data"
    / "reports"
    / "ai_daily_report.md"
)


load_dotenv(ENV_PATH)


RADAR_ANALYST = Agent(
    name="Radar Analyst",
    instructions=(
        "You are a careful financial-market research assistant. "
        "You receive deterministic scores generated by a Python radar. "
        "Treat supplied scores as model outputs, not objective facts. "
        "Do not invent prices, metrics, headlines, events, forecasts, "
        "returns, or price targets. "
        "Explain conflicts between technical, fundamental, and news scores. "
        "Clearly state uncertainty and material risks. "
        "Do not provide personalized investment advice. "
        "Write a concise professional English report in Markdown. "
        "Follow the requested section structure exactly."
    ),
)


def _ensure_api_key() -> None:
    """Ensure that an OpenAI API key is configured."""

    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError(
            "OPENAI_API_KEY was not found. "
            "Add it to the project .env file."
        )


def _load_latest_ranking() -> pd.DataFrame:
    """Load and validate the newest radar ranking."""

    if not LATEST_REPORT_PATH.exists():
        raise FileNotFoundError(
            "radar_latest.csv was not found. "
            "Run `python -m src.main` first."
        )

    report = pd.read_csv(LATEST_REPORT_PATH)

    required_columns = {
        "rank",
        "ticker",
        "overall_score",
        "technical_score",
        "fundamental_score",
        "news_score",
        "signal",
        "confidence",
        "technical_signal",
        "news_sentiment",
    }

    missing_columns = required_columns.difference(report.columns)

    if missing_columns:
        missing_text = ", ".join(sorted(missing_columns))

        raise ValueError(
            "radar_latest.csv is missing required columns: "
            f"{missing_text}"
        )

    if report.empty:
        raise ValueError(
            "radar_latest.csv contains no rows."
        )

    return report.sort_values(
        by="rank",
        ascending=True,
    )


def _format_asset_row(
    row: pd.Series,
) -> str:
    """Format one radar result for the analyst prompt."""

    fundamental_score = int(row["fundamental_score"])

    if fundamental_score < 0:
        fundamental_text = "Not applicable"
    else:
        fundamental_text = f"{fundamental_score}/100"

    return (
        f"Rank: {int(row['rank'])}\n"
        f"Ticker: {row['ticker']}\n"
        f"Final recommendation: {row['signal']}\n"
        f"Overall score: {int(row['overall_score'])}/100\n"
        f"Technical score: {int(row['technical_score'])}/100\n"
        f"Technical signal: {row['technical_signal']}\n"
        f"Fundamental score: {fundamental_text}\n"
        f"News score: {int(row['news_score'])}/100\n"
        f"News sentiment: {row['news_sentiment']}\n"
        f"Decision confidence: {int(row['confidence'])}%"
    )


def _build_analyst_prompt(
    report: pd.DataFrame,
    top_n: int,
) -> str:
    """Build a grounded prompt from the highest-ranked assets."""

    selected = report.head(top_n)

    assets = "\n\n---\n\n".join(
        _format_asset_row(row)
        for _, row in selected.iterrows()
    )

    return f"""
Analyze the following AI-Stock-Radar results.

These scores were generated by deterministic Python rules.
Do not treat them as guaranteed predictions.

ASSETS
======

{assets}

Write the report using exactly these Markdown sections:

# AI Stock Radar Daily Brief

## Executive Summary

Summarize the overall radar condition in no more than four sentences.

## Ranked Candidates

Analyze each supplied asset in ranking order.

For every asset include:
- final recommendation
- overall score
- technical interpretation
- fundamental interpretation
- news interpretation
- main contradiction or weakness

## Best Balanced Candidate

Select the asset with the strongest balance across the available inputs.
This does not necessarily have to be rank number one.
Explain the choice.

## Highest Momentum Candidate

Identify the strongest technical-momentum candidate.
Explain its main risk.

## Key Risks

List the most important limitations, score conflicts, and data risks.

## Conclusion

Give a short research conclusion.
State clearly that this is a model-generated research summary,
not personalized investment advice.
""".strip()


def generate_ai_report(
    top_n: int = 5,
) -> str:
    """Generate and save an AI analysis of the latest radar ranking."""

    if top_n < 1:
        raise ValueError(
            "top_n must be at least 1."
        )

    _ensure_api_key()

    report = _load_latest_ranking()

    prompt = _build_analyst_prompt(
        report=report,
        top_n=top_n,
    )

    result = Runner.run_sync(
        RADAR_ANALYST,
        prompt,
    )

    final_output = str(result.final_output).strip()

    if not final_output:
        raise RuntimeError(
            "The OpenAI analyst returned an empty report."
        )

    AI_REPORT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    AI_REPORT_PATH.write_text(
        final_output,
        encoding="utf-8",
    )

    return final_output


def get_ai_report_path() -> Path:
    """Return the generated AI report path."""

    return AI_REPORT_PATH